[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'
on_idle = 1
[[plugins]]
repo = 'tpope/vim-speeddating'
on_idle = 1
[[plugins]]
repo =  'qpkorr/vim-bufkill'
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'kana/vim-operator-replace'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'simeji/winresizer'
[[plugins]]
repo = 'terryma/vim-expand-region'
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''[[plugins]]
repo =  'cohama/lexima.vim'
[[plugins]]
repo =  'simeji/winresizer'
[[plugins]]
repo =  'Shougo/neomru.vim'
[[plugins]]
repo =  'Shougo/denite.nvim'
[[plugins]]
repo =  'edkolev/tmuxline.vim'
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
# repo = 'kannokanno/previm'
repo = 'suan/vim-instant-markdown'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo ='vim-airline/vim-airline-themes'

[[plugins]]
repo ='reireias/vim-cheatsheet'


[[plugins]]
repo ='vim-airline/vim-airline'
[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'KKPMW/moonshine-vim'
repo = 'tomasr/molokai'

[[plugins]] # カラースキーマ
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
# 検索ヒット数を表示する
repo = 'osyo-manga/vim-anzu'

[[plugins]]
# Vimからブラウザを開く
repo = 'tyru/open-browser.vim'

[[plugins]] # インデントを見やすく
repo = 'Yggdroot/indentLine'

[[plugins]] # 補完
repo = 'Shougo/neocomplete.vim'

[[plugins]] # スニペット
repo = 'Shougo/neosnippet'

[[plugins]] # スニペット
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'tyru/caw.vim'


[[plugins]]
repo = 'thinca/vim-quickrun'


 [[plugins]]
 repo='vim-scripts/HybridText'
hook_add='''
 autocmd BufEnter * |
if &filetype == ""  |
 setlocal ft=hybrid |
 endif
'''
[[plugins]]
 repo = 'vim-scripts/vim-auto-save'
[[plugins]]
 repo = 'kana/vim-submode'
[[plugins]]
 repo = 'easymotion/vim-easymotion'
[[plugins]]
 repo = 'haya14busa/vim-easymotion'
[[plugins]]
 repo = 'zchee/deoplete-jedi'
[[plugins]]
 repo = 'w0rp/ale'
[[plugins]] 
 repo = 'Vimjas/vim-python-pep8-indent'
[[plugins]] 
 repo = 'cocopon/iceberg.vim'
